### ISSUE TITLE
home page interface

### ISSUE THREAD

**Issue by donglinwu6066** [COMP539-Snaplink/frontend#4]

**Comment by donglinwu6066** [comment]
When the page window is in full screen (height exceeds a certain threshold), the layout will run off.
![Image](https://github.com/COMP539-Snaplink/frontend/assets/47176444/4a14cdcb-17a3-4114-89cd-e1d4c76c972f)

**Comment by h200920091** [comment]
I have changed the layout. Please check if the issue has been resolved.

**Comment by donglinwu6066** [comment]
When the user is not logged in, "Customized" should be displayed with a grey background to indicate it cannot be entered. It becomes editable only after the user logs in.
